# Generated by Django 3.2.7 on 2021-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_hero_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='Enter Description Here'),
        ),
    ]
