# Generated by Django 3.2.7 on 2021-10-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=100)),
                ('description', models.TextField(default='Enter Description Here')),
                ('strength', models.CharField(default='Enter Strength Here', max_length=100)),
                ('weakness', models.CharField(default='Enter Weakness Here', max_length=100)),
                ('image', models.CharField(default='\\static\\images\\Bear.200.png', max_length=1000)),
            ],
        ),
    ]
