# Generated by Django 3.2.7 on 2021-10-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='\\static\\images\x08ear.200.png', max_length=1000),
        ),
    ]
