# Generated by Django 3.2.7 on 2021-10-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='Enter Markdown File Here'),
        ),
    ]
