# Generated by Django 3.2.7 on 2021-09-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='description',
        ),
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.CharField(default='String', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
